/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Toolkit;


/**
 *
 * @author CHRIS
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomeAdmin() {
        initComponents();
        IconHome1.setVisible(false);
        IconData2.setVisible(false);
        IconPinjam2.setVisible(false);
        IconKembali2.setVisible(false);
        IconAdmin2.setVisible(false);
        ProfilePanel1.setVisible(false);
        ContentProfilePanel.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        ProfilePanel1 = new keeptoo.KGradientPanel();
        ProfilePanel2 = new keeptoo.KGradientPanel();
        Profile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TopbarPanel = new keeptoo.GradientPanel();
        Logo = new javax.swing.JLabel();
        LogoTitle1 = new javax.swing.JLabel();
        LogoTitle2 = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        UserHomeAdminIcon = new javax.swing.JLabel();
        SidebarPanel = new keeptoo.GradientPanel();
        HomePanel = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        IconHomePanel = new javax.swing.JPanel();
        IconHome1 = new javax.swing.JLabel();
        IconHome2 = new javax.swing.JLabel();
        DataPanel = new javax.swing.JPanel();
        DataLabel = new javax.swing.JLabel();
        IconDataPanel = new javax.swing.JPanel();
        IconData1 = new javax.swing.JLabel();
        IconData2 = new javax.swing.JLabel();
        PinjamPanel = new javax.swing.JPanel();
        PinjamLabel = new javax.swing.JLabel();
        IconPinjamPanel = new javax.swing.JPanel();
        IconPinjam1 = new javax.swing.JLabel();
        IconPinjam2 = new javax.swing.JLabel();
        KembaliPanel = new javax.swing.JPanel();
        KembaliLabel = new javax.swing.JLabel();
        IconKembaliPanel = new javax.swing.JPanel();
        IconKembali1 = new javax.swing.JLabel();
        IconKembali2 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        AdminLabel = new javax.swing.JLabel();
        IconAdminiPanel = new javax.swing.JPanel();
        IconAdmin1 = new javax.swing.JLabel();
        IconAdmin2 = new javax.swing.JLabel();
        ContentProfilePanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Information = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 239, 240));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        BackgroundPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundPanelMouseClicked(evt);
            }
        });
        BackgroundPanel.setLayout(null);

        ProfilePanel1.setkBorderRadius(50);
        ProfilePanel1.setkEndColor(new java.awt.Color(13, 79, 170));
        ProfilePanel1.setkGradientFocus(300);
        ProfilePanel1.setkStartColor(new java.awt.Color(73, 196, 241));
        ProfilePanel1.setOpaque(false);
        ProfilePanel1.setPreferredSize(new java.awt.Dimension(130, 100));
        ProfilePanel1.setLayout(null);

        ProfilePanel2.setBackground(new java.awt.Color(255, 255, 255));
        ProfilePanel2.setkBorderRadius(40);
        ProfilePanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        ProfilePanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        ProfilePanel2.setOpaque(false);
        ProfilePanel2.setPreferredSize(new java.awt.Dimension(124, 94));
        ProfilePanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 180, 10));

        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.setOpaque(false);
        Profile.setPreferredSize(new java.awt.Dimension(110, 30));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        Profile.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 20));
        Profile.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 100, 100));
        jLabel3.setText("Profile");
        jLabel3.setPreferredSize(new java.awt.Dimension(55, 20));
        Profile.add(jLabel3);

        ProfilePanel2.add(Profile);

        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.setOpaque(false);
        Logout.setPreferredSize(new java.awt.Dimension(110, 30));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(20, 20));
        Logout.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 100, 100));
        jLabel5.setText("Log out");
        jLabel5.setPreferredSize(new java.awt.Dimension(55, 20));
        Logout.add(jLabel5);

        ProfilePanel2.add(Logout);

        ProfilePanel1.add(ProfilePanel2);
        ProfilePanel2.setBounds(3, 3, 124, 94);

        BackgroundPanel.add(ProfilePanel1);
        ProfilePanel1.setBounds(1206, 80, 130, 100);

        TopbarPanel.setkEndColor(new java.awt.Color(73, 196, 241));
        TopbarPanel.setkGradientFocus(2000);
        TopbarPanel.setkStartColor(new java.awt.Color(13, 79, 170));
        TopbarPanel.setkTransparentControls(false);
        TopbarPanel.setPreferredSize(new java.awt.Dimension(1366, 110));
        TopbarPanel.setLayout(null);

        Logo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(100, 100));
        Logo.setMinimumSize(new java.awt.Dimension(0, 0));
        TopbarPanel.add(Logo);
        Logo.setBounds(30, 30, 50, 50);

        LogoTitle1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LogoTitle1.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle1.setText("WORKSHOP TOOLS MANAGEMENT SYSTEM");
        TopbarPanel.add(LogoTitle1);
        LogoTitle1.setBounds(95, 30, 482, 32);

        LogoTitle2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        LogoTitle2.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle2.setText("SMK CENDEKIA BATUJAJAR");
        TopbarPanel.add(LogoTitle2);
        LogoTitle2.setBounds(95, 60, 184, 21);

        UserPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserPanel.setOpaque(false);
        UserPanel.setPreferredSize(new java.awt.Dimension(200, 50));
        UserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserPanelMouseClicked(evt);
            }
        });
        UserPanel.setLayout(null);

        UserHomeAdminLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        UserHomeAdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserHomeAdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserHomeAdminLabel.setPreferredSize(new java.awt.Dimension(125, 20));
        UserPanel.add(UserHomeAdminLabel);
        UserHomeAdminLabel.setBounds(30, 15, 110, 20);

        UserHomeAdminIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserHomeAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        UserHomeAdminIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        UserPanel.add(UserHomeAdminIcon);
        UserHomeAdminIcon.setBounds(150, 0, 50, 50);

        TopbarPanel.add(UserPanel);
        UserPanel.setBounds(1136, 30, 200, 50);

        BackgroundPanel.add(TopbarPanel);
        TopbarPanel.setBounds(0, 0, 1366, 110);

        SidebarPanel.setkEndColor(new java.awt.Color(73, 196, 241));
        SidebarPanel.setkGradientFocus(750);
        SidebarPanel.setkStartColor(new java.awt.Color(13, 79, 170));
        SidebarPanel.setkTransparentControls(false);
        SidebarPanel.setPreferredSize(new java.awt.Dimension(100, 658));
        SidebarPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 150, 10));

        HomePanel.setOpaque(false);
        HomePanel.setPreferredSize(new java.awt.Dimension(75, 75));
        HomePanel.setLayout(new java.awt.BorderLayout());

        HomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");
        HomePanel.add(HomeLabel, java.awt.BorderLayout.PAGE_END);

        IconHomePanel.setOpaque(false);
        IconHomePanel.setLayout(null);

        IconHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home1.png"))); // NOI18N
        IconHome1.setPreferredSize(new java.awt.Dimension(35, 35));
        IconHomePanel.add(IconHome1);
        IconHome1.setBounds(20, 20, 35, 35);

        IconHome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home2.png"))); // NOI18N
        IconHome2.setPreferredSize(new java.awt.Dimension(35, 35));
        IconHomePanel.add(IconHome2);
        IconHome2.setBounds(20, 20, 35, 35);

        HomePanel.add(IconHomePanel, java.awt.BorderLayout.CENTER);

        SidebarPanel.add(HomePanel);

        DataPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataPanel.setOpaque(false);
        DataPanel.setPreferredSize(new java.awt.Dimension(75, 75));
        DataPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPanelMouseClicked(evt);
            }
        });
        DataPanel.setLayout(new java.awt.BorderLayout());

        DataLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        DataLabel.setForeground(new java.awt.Color(255, 255, 255));
        DataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DataLabel.setText("Database");
        DataPanel.add(DataLabel, java.awt.BorderLayout.PAGE_END);

        IconDataPanel.setOpaque(false);
        IconDataPanel.setLayout(null);

        IconData1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconData1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/database1.png"))); // NOI18N
        IconData1.setPreferredSize(new java.awt.Dimension(35, 35));
        IconDataPanel.add(IconData1);
        IconData1.setBounds(20, 20, 35, 35);

        IconData2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconData2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/database2.png"))); // NOI18N
        IconData2.setPreferredSize(new java.awt.Dimension(35, 35));
        IconDataPanel.add(IconData2);
        IconData2.setBounds(20, 20, 35, 35);

        DataPanel.add(IconDataPanel, java.awt.BorderLayout.CENTER);

        SidebarPanel.add(DataPanel);

        PinjamPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PinjamPanel.setOpaque(false);
        PinjamPanel.setPreferredSize(new java.awt.Dimension(75, 75));
        PinjamPanel.setLayout(new java.awt.BorderLayout());

        PinjamLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PinjamLabel.setForeground(new java.awt.Color(255, 255, 255));
        PinjamLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PinjamLabel.setText("Pinjam");
        PinjamPanel.add(PinjamLabel, java.awt.BorderLayout.PAGE_END);

        IconPinjamPanel.setOpaque(false);
        IconPinjamPanel.setLayout(null);

        IconPinjam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconPinjam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tb1.png"))); // NOI18N
        IconPinjam1.setPreferredSize(new java.awt.Dimension(35, 35));
        IconPinjamPanel.add(IconPinjam1);
        IconPinjam1.setBounds(20, 20, 35, 35);

        IconPinjam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconPinjam2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tb2.png"))); // NOI18N
        IconPinjam2.setPreferredSize(new java.awt.Dimension(35, 35));
        IconPinjamPanel.add(IconPinjam2);
        IconPinjam2.setBounds(20, 20, 35, 35);

        PinjamPanel.add(IconPinjamPanel, java.awt.BorderLayout.CENTER);

        SidebarPanel.add(PinjamPanel);

        KembaliPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KembaliPanel.setOpaque(false);
        KembaliPanel.setPreferredSize(new java.awt.Dimension(75, 75));
        KembaliPanel.setLayout(new java.awt.BorderLayout());

        KembaliLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        KembaliLabel.setForeground(new java.awt.Color(255, 255, 255));
        KembaliLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KembaliLabel.setText("Kembali");
        KembaliPanel.add(KembaliLabel, java.awt.BorderLayout.PAGE_END);

        IconKembaliPanel.setOpaque(false);
        IconKembaliPanel.setLayout(null);

        IconKembali1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconKembali1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tb3.png"))); // NOI18N
        IconKembali1.setPreferredSize(new java.awt.Dimension(35, 35));
        IconKembaliPanel.add(IconKembali1);
        IconKembali1.setBounds(20, 20, 35, 35);

        IconKembali2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconKembali2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tb4.png"))); // NOI18N
        IconKembali2.setPreferredSize(new java.awt.Dimension(35, 35));
        IconKembaliPanel.add(IconKembali2);
        IconKembali2.setBounds(20, 20, 35, 35);

        KembaliPanel.add(IconKembaliPanel, java.awt.BorderLayout.CENTER);

        SidebarPanel.add(KembaliPanel);

        AdminPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminPanel.setOpaque(false);
        AdminPanel.setPreferredSize(new java.awt.Dimension(75, 75));
        AdminPanel.setLayout(new java.awt.BorderLayout());

        AdminLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminLabel.setText("Kembali");
        AdminPanel.add(AdminLabel, java.awt.BorderLayout.PAGE_END);

        IconAdminiPanel.setOpaque(false);
        IconAdminiPanel.setLayout(null);

        IconAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconAdmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin1.png"))); // NOI18N
        IconAdmin1.setPreferredSize(new java.awt.Dimension(35, 35));
        IconAdminiPanel.add(IconAdmin1);
        IconAdmin1.setBounds(20, 20, 35, 35);

        IconAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconAdmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin2.png"))); // NOI18N
        IconAdmin2.setPreferredSize(new java.awt.Dimension(35, 35));
        IconAdminiPanel.add(IconAdmin2);
        IconAdmin2.setBounds(20, 20, 35, 35);

        AdminPanel.add(IconAdminiPanel, java.awt.BorderLayout.CENTER);

        SidebarPanel.add(AdminPanel);

        BackgroundPanel.add(SidebarPanel);
        SidebarPanel.setBounds(0, 110, 100, 658);

        ContentProfilePanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentProfilePanel.setPreferredSize(new java.awt.Dimension(1266, 658));
        ContentProfilePanel.setLayout(null);

        ProfileAdmin.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ProfileAdmin.setPreferredSize(new java.awt.Dimension(600, 35));
        ContentProfilePanel.add(ProfileAdmin);
        ProfileAdmin.setBounds(30, 30, 600, 35);

        BackgroundPanel.add(ContentProfilePanel);
        ContentProfilePanel.setBounds(100, 110, 1266, 658);

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setPreferredSize(new java.awt.Dimension(1266, 658));
        ContentPanel.setLayout(null);

        WelcomeHomeAdminLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        WelcomeHomeAdminLabel.setPreferredSize(new java.awt.Dimension(450, 35));
        ContentPanel.add(WelcomeHomeAdminLabel);
        WelcomeHomeAdminLabel.setBounds(30, 30, 450, 35);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(535, 455));
        ContentPanel.add(jLabel1);
        jLabel1.setBounds(30, 175, 535, 455);

        Information.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Information.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Information.setText("<html>\nBengkel Listrik Teknik Instalasi Tenaga Listrik SMK Cendekia Batujajar memiliki\nberbagai peralatan yang sangat lengkap guna menunjang kebutuhan kegiatan\npraktikum siswa, seperti tersedianya berbagai macam obeng, saklar, kontaktor\nhingga bor duduk.\n</html>");
        Information.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Information.setPreferredSize(new java.awt.Dimension(630, 110));
        ContentPanel.add(Information);
        Information.setBounds(595, 175, 630, 110);

        BackgroundPanel.add(ContentPanel);
        ContentPanel.setBounds(100, 110, 1266, 658);

        getContentPane().add(BackgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DataPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPanelMouseClicked
        TestLogin tl = new TestLogin();
        tl.show();
        this.setVisible(false);
    }//GEN-LAST:event_DataPanelMouseClicked

    private void UserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPanelMouseClicked
        ProfilePanel1.setVisible(true);
    }//GEN-LAST:event_UserPanelMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Logins l = new Logins();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogoutMouseClicked

    private void BackgroundPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundPanelMouseClicked
        ProfilePanel1.setVisible(false);
    }//GEN-LAST:event_BackgroundPanelMouseClicked

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        ContentPanel.setVisible(false);
        ContentProfilePanel.setVisible(true);
        ProfilePanel1.setVisible(false);
    }//GEN-LAST:event_ProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel ContentProfilePanel;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel IconAdmin1;
    private javax.swing.JLabel IconAdmin2;
    private javax.swing.JPanel IconAdminiPanel;
    private javax.swing.JLabel IconData1;
    private javax.swing.JLabel IconData2;
    private javax.swing.JPanel IconDataPanel;
    private javax.swing.JLabel IconHome1;
    private javax.swing.JLabel IconHome2;
    private javax.swing.JPanel IconHomePanel;
    private javax.swing.JLabel IconKembali1;
    private javax.swing.JLabel IconKembali2;
    private javax.swing.JPanel IconKembaliPanel;
    private javax.swing.JLabel IconPinjam1;
    private javax.swing.JLabel IconPinjam2;
    private javax.swing.JPanel IconPinjamPanel;
    private javax.swing.JLabel Information;
    private javax.swing.JLabel KembaliLabel;
    private javax.swing.JPanel KembaliPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoTitle1;
    private javax.swing.JLabel LogoTitle2;
    private javax.swing.JPanel Logout;
    private javax.swing.JLabel PinjamLabel;
    private javax.swing.JPanel PinjamPanel;
    private javax.swing.JPanel Profile;
    public static final javax.swing.JLabel ProfileAdmin = new javax.swing.JLabel();
    private keeptoo.KGradientPanel ProfilePanel1;
    private keeptoo.KGradientPanel ProfilePanel2;
    private keeptoo.GradientPanel SidebarPanel;
    private keeptoo.GradientPanel TopbarPanel;
    private javax.swing.JLabel UserHomeAdminIcon;
    public static final javax.swing.JLabel UserHomeAdminLabel = new javax.swing.JLabel();
    private javax.swing.JPanel UserPanel;
    public static final javax.swing.JLabel WelcomeHomeAdminLabel = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
