/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static src.HomeAdmin.WelcomeHomeAdminLabel;
import static src.HomeAdmin.UserHomeAdminLabel;

/**
 *
 * @author CHRIS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public Login() {
        initComponents();
        Close2.setVisible(false);
        ForgotPanel.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
        
        JLabel[] close1 = {Close1};
        for (JLabel cls1 : close1) {
            cls1.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {}

                @Override
                public void mousePressed(MouseEvent me) {}

                @Override
                public void mouseReleased(MouseEvent me) {}

                @Override
                public void mouseEntered(MouseEvent me) {
                    Close1.setVisible(false);
                    Close2.setVisible(true);
                }

                @Override
                public void mouseExited(MouseEvent me) {}
            });
        }
        
        JLabel[] close2 = {Close2};
        for (JLabel cls2 : close2) {
            cls2.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                    System.exit(0);
                }

                @Override
                public void mousePressed(MouseEvent me) {}

                @Override
                public void mouseReleased(MouseEvent me) {}

                @Override
                public void mouseEntered(MouseEvent me) {}

                @Override
                public void mouseExited(MouseEvent me) {
                    Close1.setVisible(true);
                    Close2.setVisible(false);
                }
            });
        }
    }
    
    String clear;
    private void reset() {
        UsernameField.setText(clear);
        PasswordField.setText(clear);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        gradientPanel1 = new keeptoo.GradientPanel();
        Logo = new javax.swing.JLabel();
        LogoTitle1 = new javax.swing.JLabel();
        LogoTitle2 = new javax.swing.JLabel();
        Close1 = new javax.swing.JLabel();
        Close2 = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        Information = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new keeptoo.KButton();
        ForgotLabel = new javax.swing.JLabel();
        ForgotPanel = new javax.swing.JPanel();
        PasswordRecovery = new javax.swing.JLabel();
        UsernameForgotLabel = new javax.swing.JLabel();
        UsernameForgotField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        NewPasswordLabel = new javax.swing.JLabel();
        NewPassField = new javax.swing.JPasswordField();
        ResetPassButton = new keeptoo.KButton();
        Search = new javax.swing.JLabel();
        Checked = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 239, 240));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        BackgroundPanel.setLayout(null);

        gradientPanel1.setkEndColor(new java.awt.Color(73, 196, 241));
        gradientPanel1.setkGradientFocus(2000);
        gradientPanel1.setkStartColor(new java.awt.Color(13, 79, 170));
        gradientPanel1.setkTransparentControls(false);
        gradientPanel1.setPreferredSize(new java.awt.Dimension(1366, 110));
        gradientPanel1.setLayout(null);

        Logo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(100, 100));
        Logo.setMinimumSize(new java.awt.Dimension(0, 0));
        gradientPanel1.add(Logo);
        Logo.setBounds(30, 30, 50, 50);

        LogoTitle1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LogoTitle1.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle1.setText("WORKSHOP TOOLS MANAGEMENT SYSTEM");
        gradientPanel1.add(LogoTitle1);
        LogoTitle1.setBounds(95, 30, 482, 32);

        LogoTitle2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        LogoTitle2.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle2.setText("SMK CENDEKIA BATUJAJAR");
        gradientPanel1.add(LogoTitle2);
        LogoTitle2.setBounds(95, 60, 184, 21);

        Close1.setForeground(new java.awt.Color(255, 255, 255));
        Close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout1.png"))); // NOI18N
        gradientPanel1.add(Close1);
        Close1.setBounds(1316, 30, 20, 20);

        Close2.setForeground(new java.awt.Color(255, 255, 255));
        Close2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout2.png"))); // NOI18N
        gradientPanel1.add(Close2);
        Close2.setBounds(1316, 30, 20, 20);

        BackgroundPanel.add(gradientPanel1);
        gradientPanel1.setBounds(0, 0, 1366, 110);

        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        Image.setPreferredSize(new java.awt.Dimension(535, 455));
        BackgroundPanel.add(Image);
        Image.setBounds(150, 290, 535, 455);

        Information.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Information.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Information.setText("<html>\nBengkel Listrik Teknik Instalasi Tenaga Listrik SMK Cendekia Batujajar memiliki berbagai\nperalatan yang sangat lengkap guna menunjang kebutuhan kegiatan praktikum siswa,\nseperti tersedianya berbagai macam obeng, saklar, kontaktor hingga bor duduk.\n</html>");
        Information.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Information.setPreferredSize(new java.awt.Dimension(700, 110));
        BackgroundPanel.add(Information);
        Information.setBounds(80, 170, 700, 110);

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        LoginPanel.setPreferredSize(new java.awt.Dimension(420, 538));

        LoginLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(51, 51, 51));
        LoginLabel.setText("Login");

        UsernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        UsernameLabel.setText("Username");
        UsernameLabel.setPreferredSize(new java.awt.Dimension(360, 22));

        UsernameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(51, 51, 51));
        UsernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        UsernameField.setOpaque(false);
        UsernameField.setPreferredSize(new java.awt.Dimension(360, 24));
        UsernameField.setSelectedTextColor(new java.awt.Color(0, 120, 215));
        UsernameField.setSelectionColor(new java.awt.Color(255, 255, 255));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        PasswordLabel.setText("Password");
        PasswordLabel.setPreferredSize(new java.awt.Dimension(360, 22));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(51, 51, 51));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        PasswordField.setOpaque(false);
        PasswordField.setPreferredSize(new java.awt.Dimension(360, 24));
        PasswordField.setSelectedTextColor(new java.awt.Color(0, 120, 215));
        PasswordField.setSelectionColor(new java.awt.Color(255, 255, 255));

        LoginButton.setText("Log in");
        LoginButton.setBorderPainted(false);
        LoginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LoginButton.setkAllowGradient(false);
        LoginButton.setkBackGroundColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkBorderRadius(15);
        LoginButton.setkEndColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkHoverColor(new java.awt.Color(73, 196, 241));
        LoginButton.setkHoverEndColor(new java.awt.Color(73, 196, 241));
        LoginButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        LoginButton.setkHoverStartColor(new java.awt.Color(73, 196, 241));
        LoginButton.setkIndicatorColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkIndicatorThickness(0);
        LoginButton.setkPressedColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkStartColor(new java.awt.Color(13, 79, 170));
        LoginButton.setOpaque(false);
        LoginButton.setPreferredSize(new java.awt.Dimension(360, 40));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        ForgotLabel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        ForgotLabel.setForeground(new java.awt.Color(102, 102, 102));
        ForgotLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForgotLabel.setText("Forgot password ?");
        ForgotLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotLabel.setPreferredSize(new java.awt.Dimension(360, 14));
        ForgotLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginLabel)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForgotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LoginLabel)
                .addGap(50, 50, 50)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ForgotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        BackgroundPanel.add(LoginPanel);
        LoginPanel.setBounds(866, 170, 420, 538);

        ForgotPanel.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ForgotPanel.setPreferredSize(new java.awt.Dimension(420, 538));
        ForgotPanel.setLayout(null);

        PasswordRecovery.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        PasswordRecovery.setForeground(new java.awt.Color(51, 51, 51));
        PasswordRecovery.setText("Password Recovery");
        ForgotPanel.add(PasswordRecovery);
        PasswordRecovery.setBounds(32, 32, 208, 32);

        UsernameForgotLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UsernameForgotLabel.setForeground(new java.awt.Color(51, 51, 51));
        UsernameForgotLabel.setText("Username");
        UsernameForgotLabel.setPreferredSize(new java.awt.Dimension(360, 22));
        ForgotPanel.add(UsernameForgotLabel);
        UsernameForgotLabel.setBounds(32, 114, 360, 22);

        UsernameForgotField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsernameForgotField.setForeground(new java.awt.Color(51, 51, 51));
        UsernameForgotField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        UsernameForgotField.setOpaque(false);
        UsernameForgotField.setPreferredSize(new java.awt.Dimension(330, 24));
        UsernameForgotField.setSelectedTextColor(new java.awt.Color(0, 120, 215));
        UsernameForgotField.setSelectionColor(new java.awt.Color(255, 255, 255));
        ForgotPanel.add(UsernameForgotField);
        UsernameForgotField.setBounds(32, 141, 330, 24);

        EmailLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(51, 51, 51));
        EmailLabel.setText("Email");
        EmailLabel.setPreferredSize(new java.awt.Dimension(360, 22));
        ForgotPanel.add(EmailLabel);
        EmailLabel.setBounds(32, 185, 360, 22);

        EmailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailField.setForeground(new java.awt.Color(51, 51, 51));
        EmailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        EmailField.setOpaque(false);
        EmailField.setPreferredSize(new java.awt.Dimension(360, 24));
        EmailField.setSelectedTextColor(new java.awt.Color(0, 120, 215));
        EmailField.setSelectionColor(new java.awt.Color(255, 255, 255));
        ForgotPanel.add(EmailField);
        EmailField.setBounds(32, 212, 360, 24);

        NewPasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        NewPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        NewPasswordLabel.setText("New Password");
        NewPasswordLabel.setPreferredSize(new java.awt.Dimension(360, 22));
        ForgotPanel.add(NewPasswordLabel);
        NewPasswordLabel.setBounds(32, 256, 360, 22);

        NewPassField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewPassField.setForeground(new java.awt.Color(51, 51, 51));
        NewPassField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        NewPassField.setOpaque(false);
        NewPassField.setPreferredSize(new java.awt.Dimension(360, 24));
        NewPassField.setSelectedTextColor(new java.awt.Color(0, 120, 215));
        NewPassField.setSelectionColor(new java.awt.Color(255, 255, 255));
        ForgotPanel.add(NewPassField);
        NewPassField.setBounds(32, 283, 360, 24);

        ResetPassButton.setText("Reset Password");
        ResetPassButton.setBorderPainted(false);
        ResetPassButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ResetPassButton.setkAllowGradient(false);
        ResetPassButton.setkBackGroundColor(new java.awt.Color(13, 79, 170));
        ResetPassButton.setkBorderRadius(15);
        ResetPassButton.setkEndColor(new java.awt.Color(13, 79, 170));
        ResetPassButton.setkHoverColor(new java.awt.Color(73, 196, 241));
        ResetPassButton.setkHoverEndColor(new java.awt.Color(73, 196, 241));
        ResetPassButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ResetPassButton.setkHoverStartColor(new java.awt.Color(73, 196, 241));
        ResetPassButton.setkIndicatorColor(new java.awt.Color(13, 79, 170));
        ResetPassButton.setkIndicatorThickness(0);
        ResetPassButton.setkPressedColor(new java.awt.Color(13, 79, 170));
        ResetPassButton.setkStartColor(new java.awt.Color(13, 79, 170));
        ResetPassButton.setOpaque(false);
        ResetPassButton.setPreferredSize(new java.awt.Dimension(360, 40));
        ForgotPanel.add(ResetPassButton);
        ResetPassButton.setBounds(32, 347, 360, 40);

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_20px.png"))); // NOI18N
        Search.setOpaque(true);
        Search.setPreferredSize(new java.awt.Dimension(24, 24));
        ForgotPanel.add(Search);
        Search.setBounds(366, 141, 24, 24);

        Checked.setBackground(new java.awt.Color(255, 255, 255));
        Checked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Checked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checked_20px.png"))); // NOI18N
        Checked.setOpaque(true);
        Checked.setPreferredSize(new java.awt.Dimension(24, 24));
        ForgotPanel.add(Checked);
        Checked.setBounds(366, 141, 24, 24);

        BackgroundPanel.add(ForgotPanel);
        ForgotPanel.setBounds(866, 170, 420, 538);

        getContentPane().add(BackgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ForgotLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotLabelMouseClicked
        LoginPanel.setVisible(false);
        ForgotPanel.setVisible(true);
    }//GEN-LAST:event_ForgotLabelMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        
        String username = UsernameField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String sql = "SELECT * FROM `user` WHERE `username` = ? AND `password` = ?";
        
        try {
            ps = ConnectionDatabase.getConnection().prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            rs = ps.executeQuery();
            if (rs.next()) {
                String level = rs.getString(10);
                if (level.equals("Kepala")) {
                    UserHomeAdminLabel.setText(rs.getString(2));
                    WelcomeHomeAdminLabel.setText("Hai " + rs.getString(2) + ", Selamat Datang Ke Sistem!");
                    HomeAdmin ho = new HomeAdmin();
                    ho.setVisible(true);
//                    ho.show();
                    this.setVisible(false);
                } else if (level.equals("Administrator")) {
                    TestLogin tl = new TestLogin();
                    tl.setVisible(true);
                    this.setVisible(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect ID or Password", "Login Failed", JOptionPane.INFORMATION_MESSAGE);
                reset();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel Checked;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close2;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel ForgotLabel;
    private javax.swing.JPanel ForgotPanel;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Information;
    private keeptoo.KButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoTitle1;
    private javax.swing.JLabel LogoTitle2;
    private javax.swing.JPasswordField NewPassField;
    private javax.swing.JLabel NewPasswordLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordRecovery;
    private keeptoo.KButton ResetPassButton;
    private javax.swing.JLabel Search;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JTextField UsernameForgotField;
    private javax.swing.JLabel UsernameForgotLabel;
    private javax.swing.JLabel UsernameLabel;
    private keeptoo.GradientPanel gradientPanel1;
    // End of variables declaration//GEN-END:variables
}
