/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static src.HomeAdmin.ProfileAdmin;
import static src.HomeAdmin.WelcomeHomeAdminLabel;
import static src.HomeAdmin.UserHomeAdminLabel;

/**
 *
 * @author CHRIS
 */
public class Logins extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public Logins() {
        initComponents();
        Close2.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
        
        JLabel[] close1 = {Close1};
        for (JLabel cls1 : close1) {
            cls1.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {}

                @Override
                public void mousePressed(MouseEvent me) {}

                @Override
                public void mouseReleased(MouseEvent me) {}

                @Override
                public void mouseEntered(MouseEvent me) {
                    Close1.setVisible(false);
                    Close2.setVisible(true);
                }

                @Override
                public void mouseExited(MouseEvent me) {}
            });
        }
        
        JLabel[] close2 = {Close2};
        for (JLabel cls2 : close2) {
            cls2.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent me) {
                    System.exit(0);
                }

                @Override
                public void mousePressed(MouseEvent me) {}

                @Override
                public void mouseReleased(MouseEvent me) {}

                @Override
                public void mouseEntered(MouseEvent me) {}

                @Override
                public void mouseExited(MouseEvent me) {
                    Close1.setVisible(true);
                    Close2.setVisible(false);
                }
            });
        }
    }
    
    String clear;
    private void reset() {
        UsernameField.setText(clear);
        PasswordField.setText(clear);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        ContentLeftPanel = new keeptoo.GradientPanel();
        LogoImage = new javax.swing.JLabel();
        LogoTitle1 = new javax.swing.JLabel();
        LogoTitle2 = new javax.swing.JLabel();
        LogoTitle3 = new javax.swing.JLabel();
        ContentRightPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new keeptoo.KButton();
        Close1 = new javax.swing.JLabel();
        Close2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 239, 240));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(800, 460));
        BackgroundPanel.setLayout(null);

        ContentLeftPanel.setkEndColor(new java.awt.Color(73, 196, 241));
        ContentLeftPanel.setkGradientFocus(250);
        ContentLeftPanel.setkStartColor(new java.awt.Color(13, 79, 170));
        ContentLeftPanel.setPreferredSize(new java.awt.Dimension(400, 460));
        ContentLeftPanel.setLayout(null);

        LogoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
        LogoImage.setPreferredSize(new java.awt.Dimension(200, 200));
        ContentLeftPanel.add(LogoImage);
        LogoImage.setBounds(100, 75, 200, 200);

        LogoTitle1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        LogoTitle1.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoTitle1.setText("WORKSHOP TOOLS");
        ContentLeftPanel.add(LogoTitle1);
        LogoTitle1.setBounds(124, 285, 152, 24);

        LogoTitle2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        LogoTitle2.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoTitle2.setText("MANAGEMENT SYSTEM");
        ContentLeftPanel.add(LogoTitle2);
        LogoTitle2.setBounds(107, 310, 186, 24);

        LogoTitle3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        LogoTitle3.setForeground(new java.awt.Color(255, 255, 255));
        LogoTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoTitle3.setText("SMK CENDEKIA BATUJAJAR");
        ContentLeftPanel.add(LogoTitle3);
        LogoTitle3.setBounds(93, 335, 214, 24);

        BackgroundPanel.add(ContentLeftPanel);
        ContentLeftPanel.setBounds(0, 0, 400, 460);

        ContentRightPanel.setOpaque(false);
        ContentRightPanel.setPreferredSize(new java.awt.Dimension(400, 460));
        ContentRightPanel.setLayout(null);

        LoginLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(100, 100, 100));
        LoginLabel.setText("Login");
        ContentRightPanel.add(LoginLabel);
        LoginLabel.setBounds(50, 30, 60, 32);

        UsernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(100, 100, 100));
        UsernameLabel.setText("Username");
        ContentRightPanel.add(UsernameLabel);
        UsernameLabel.setBounds(50, 130, 84, 25);

        UsernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(75, 75, 75));
        UsernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(150, 150, 150)));
        UsernameField.setPreferredSize(new java.awt.Dimension(300, 26));
        ContentRightPanel.add(UsernameField);
        UsernameField.setBounds(50, 165, 300, 26);

        PasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(100, 100, 100));
        PasswordLabel.setText("Password");
        ContentRightPanel.add(PasswordLabel);
        PasswordLabel.setBounds(50, 230, 79, 25);

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(75, 75, 75));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(150, 150, 150)));
        PasswordField.setPreferredSize(new java.awt.Dimension(300, 26));
        ContentRightPanel.add(PasswordField);
        PasswordField.setBounds(50, 265, 300, 26);

        LoginButton.setBorder(null);
        LoginButton.setText("Log in");
        LoginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LoginButton.setkAllowGradient(false);
        LoginButton.setkBackGroundColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkBorderRadius(15);
        LoginButton.setkEndColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkHoverColor(new java.awt.Color(73, 196, 241));
        LoginButton.setkHoverEndColor(new java.awt.Color(73, 196, 241));
        LoginButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        LoginButton.setkHoverStartColor(new java.awt.Color(73, 196, 241));
        LoginButton.setkIndicatorColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkIndicatorThickness(0);
        LoginButton.setkPressedColor(new java.awt.Color(13, 79, 170));
        LoginButton.setkStartColor(new java.awt.Color(13, 79, 170));
        LoginButton.setPreferredSize(new java.awt.Dimension(300, 45));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        ContentRightPanel.add(LoginButton);
        LoginButton.setBounds(50, 350, 300, 45);

        Close1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close1.png"))); // NOI18N
        Close1.setPreferredSize(new java.awt.Dimension(20, 20));
        ContentRightPanel.add(Close1);
        Close1.setBounds(370, 10, 20, 20);

        Close2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close2.png"))); // NOI18N
        Close2.setPreferredSize(new java.awt.Dimension(20, 20));
        ContentRightPanel.add(Close2);
        Close2.setBounds(370, 10, 20, 20);

        BackgroundPanel.add(ContentRightPanel);
        ContentRightPanel.setBounds(400, 0, 400, 460);

        getContentPane().add(BackgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        
        String username = UsernameField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String sql = "SELECT * FROM `user` WHERE `username` = ? AND `password` = ?";
        
        try {
            ps = ConnectionDatabase.getConnection().prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            rs = ps.executeQuery();
            if (rs.next()) {
                String level = rs.getString(10);
                if (level.equals("Kepala")) {
                    UserHomeAdminLabel.setText(rs.getString(2));
                    ProfileAdmin.setText("Hai " + rs.getString(2) + ". Selamat datang di profile anda!");
                    WelcomeHomeAdminLabel.setText("Hai " + rs.getString(2) + ". Selamat datang ke sistem!");
                    HomeAdmin ha = new HomeAdmin();
                    ha.setVisible(true);
                    this.setVisible(false);
                } else if (level.equals("Administrator")) {
                    TestLogin tl = new TestLogin();
                    tl.setVisible(true);
                    this.setVisible(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect ID or Password", "Login Failed", JOptionPane.INFORMATION_MESSAGE);
                reset();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close2;
    private keeptoo.GradientPanel ContentLeftPanel;
    private javax.swing.JPanel ContentRightPanel;
    private keeptoo.KButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel LogoImage;
    private javax.swing.JLabel LogoTitle1;
    private javax.swing.JLabel LogoTitle2;
    private javax.swing.JLabel LogoTitle3;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
