/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author CHRIS
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradientPanel1 = new keeptoo.GradientPanel();
        ProgressBar = new javax.swing.JProgressBar();
        LoadingText = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 460));

        gradientPanel1.setkEndColor(new java.awt.Color(73, 196, 241));
        gradientPanel1.setkGradientFocus(1000);
        gradientPanel1.setkStartColor(new java.awt.Color(13, 79, 170));
        gradientPanel1.setLayout(null);

        ProgressBar.setPreferredSize(new java.awt.Dimension(810, 15));
        gradientPanel1.add(ProgressBar);
        ProgressBar.setBounds(-5, 450, 810, 15);

        LoadingText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingText.setForeground(new java.awt.Color(255, 255, 255));
        LoadingText.setText("Loading...");
        LoadingText.setPreferredSize(new java.awt.Dimension(200, 20));
        gradientPanel1.add(LoadingText);
        LoadingText.setBounds(5, 430, 200, 20);

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LoadingValue.setText("0 %");
        LoadingValue.setPreferredSize(new java.awt.Dimension(40, 20));
        gradientPanel1.add(LoadingValue);
        LoadingValue.setBounds(755, 430, 40, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splashscreen.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(410, 200));
        gradientPanel1.add(jLabel1);
        jLabel1.setBounds(195, 50, 410, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WORKSHOP TOOLS MANAGEMENT SYSTEM");
        gradientPanel1.add(jLabel2);
        jLabel2.setBounds(159, 270, 482, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SMK CENDEKIA BATUJAJAR");
        gradientPanel1.add(jLabel3);
        jLabel3.setBounds(279, 300, 242, 27);

        getContentPane().add(gradientPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        try {
            for(int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                sp.LoadingValue.setText(i + " %");
                if(i == 10) {
                    sp.LoadingText.setText("Turning on modules...");
                }
                if(i == 30) {
                    sp.LoadingText.setText("Loading modules...");
                }
                if(i == 60) {
                    sp.LoadingText.setText("Connecting to database...");
                }
                if(i == 80) {
                    sp.LoadingText.setText("Connection successful...");
                }
                if(i == 90) {
                    sp.LoadingText.setText("Launching application...");
                }
                sp.ProgressBar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Logins lo = new Logins();
                lo.show();
                sp.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingText;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JProgressBar ProgressBar;
    private keeptoo.GradientPanel gradientPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
