/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sourcecode;

import java.awt.Color;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chani
 */
public class DataGuru extends javax.swing.JFrame {
        Connection con;
        Statement stat;
        ResultSet rs;
        String sql;
        koneksi k;
        DefaultTableModel model;
    /**
     * Creates new form DataGuru
     */
    public DataGuru() {
        
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        tampil();
     
    }

     //FUNGSI ATAU PROSEDUR
    public void tampil(){        
        DefaultTableModel model = new DefaultTableModel ( );
        table_guru.setModel(model);
        model.addColumn("No");
        model.addColumn("NIP");
        model.addColumn("NK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        
         try{
           stat = con.createStatement( );
           sql  = "Select * from guru";
           rs   = stat.executeQuery(sql);
           int no=1;
           while(rs.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = Integer.toString(no);
                obj[1] = rs.getString("nip");
                obj[2] = rs.getString("nk");
                obj[3] = rs.getString("nama");
                obj[4] = rs.getString("jeniskelamin");
                model.addRow(obj);
                no++;
            }
            
             table_guru.setModel(model);
        } catch (SQLException e) {
            System.out.println(e);
      }
    }
    
    public void deletedata(){
        model = new DefaultTableModel ( );
        table_guru.setModel(model);
        model.addColumn("No");
        model.addColumn("NIP");
        model.addColumn("NK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        try {
            stat = con.createStatement( );
            con.createStatement().executeUpdate("DELETE FROM guru WHERE nis='"+txt_search.getText()+"'");
            rs   = stat.executeQuery(sql);
            int no=1;
            while(rs.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = Integer.toString(no);
                obj[1] = rs.getString("nip");
                obj[2] = rs.getString("nk");
                obj[3] = rs.getString("nama");
                obj[4] = rs.getString("jeniskelamin");
                model.addRow(obj);
                no++;
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ("Data tidak ditemukan dan tidak dapat dihapus"), 
            "Delete Data Guru Gagal", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void querysearch(){
        int row = table_guru.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        
        try{
           stat = con.createStatement( );
           sql  = "Select * from siswa WHERE nis='"+txt_search.getText()+"'";
                   
           rs   = stat.executeQuery(sql);

           int no=1;
           while(rs.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = Integer.toString(no);
                obj[1] = rs.getString("nip");
                obj[2] = rs.getString("nk");
                obj[3] = rs.getString("nama");
                obj[4] = rs.getString("jeniskelamin");
                model.addRow(obj);
                no++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void querysearchklik(){
        int i = table_guru.getSelectedRow();
        if(i>-1){
            txt_search.setText(model.getValueAt(i, 1).toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        panel_body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_guru = new javax.swing.JTable();
        btn_addGuru = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_lihat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_body.setBackground(new java.awt.Color(255, 255, 204));

        table_guru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "NIP", "NK", "Nama", "Jenis Kelamin"
            }
        ));
        table_guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_guruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_guru);

        btn_addGuru.setBackground(new java.awt.Color(224, 210, 255));
        btn_addGuru.setText("Add Guru");
        btn_addGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addGuruMouseExited(evt);
            }
        });
        btn_addGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addGuruActionPerformed(evt);
            }
        });

        jButton1.setText("S");

        jButton2.setText("Kembali");

        jButton3.setText("Hapus");

        btn_lihat.setText("Lihat Data");

        javax.swing.GroupLayout panel_bodyLayout = new javax.swing.GroupLayout(panel_body);
        panel_body.setLayout(panel_bodyLayout);
        panel_bodyLayout.setHorizontalGroup(
            panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bodyLayout.createSequentialGroup()
                        .addComponent(btn_addGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bodyLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_lihat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel_bodyLayout.setVerticalGroup(
            panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addGuru)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panel_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btn_lihat))
                .addContainerGap())
        );

        bgPanel.add(panel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 570, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addGuruMouseEntered
        // TODO add your handling code here:
        btn_addGuru.setBackground(new Color(147,133,255));
        
    }//GEN-LAST:event_btn_addGuruMouseEntered

    private void btn_addGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addGuruActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        TambahGuru tbhguru=new TambahGuru();
        tbhguru.setVisible(true);
    }//GEN-LAST:event_btn_addGuruActionPerformed

    private void btn_addGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addGuruMouseExited
        // TODO add your handling code here:
        btn_addGuru.setBackground(new Color(173,159,255));
    }//GEN-LAST:event_btn_addGuruMouseExited

    private void table_guruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_guruMouseClicked
        // TODO add your handling code here:
        this.querysearchklik();
    }//GEN-LAST:event_table_guruMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataGuru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btn_addGuru;
    private javax.swing.JButton btn_lihat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_body;
    private javax.swing.JTable table_guru;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
