/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smkcendekia;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class lupapassword extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
        
    public lupapassword() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellupapassword = new javax.swing.JPanel();
        txt_niplupapassword = new javax.swing.JTextField();
        txt_namalupapassword = new javax.swing.JTextField();
        txt_usernamelupapassword = new javax.swing.JTextField();
        txt_passlupapassword = new javax.swing.JPasswordField();
        txt_pass2lupapassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_simpanlupapassword = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 355));

        panellupapassword.setPreferredSize(new java.awt.Dimension(650, 350));
        panellupapassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panellupapassword.add(txt_niplupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 83, 450, 30));
        panellupapassword.add(txt_namalupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 121, 450, 30));
        panellupapassword.add(txt_usernamelupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 164, 450, 30));
        panellupapassword.add(txt_passlupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 207, 450, 30));
        panellupapassword.add(txt_pass2lupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 247, 450, 30));

        jLabel1.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText(":");
        panellupapassword.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 123, 50, 20));

        jLabel2.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Nama");
        panellupapassword.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 128, 60, 20));

        jLabel3.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Username");
        panellupapassword.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 172, -1, -1));

        jLabel4.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Password Baru");
        panellupapassword.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 212, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Tulis Ulang Password");
        panellupapassword.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 251, 130, 20));

        btn_simpanlupapassword.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpanlupapassword.setFont(new java.awt.Font("Zilla Slab SemiBold", 0, 12)); // NOI18N
        btn_simpanlupapassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/floppy-disk.png"))); // NOI18N
        btn_simpanlupapassword.setText("Simpan");
        btn_simpanlupapassword.setIconTextGap(18);
        btn_simpanlupapassword.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btn_simpanlupapassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanlupapasswordActionPerformed(evt);
            }
        });
        panellupapassword.add(btn_simpanlupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 160, 40));

        jLabel7.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("NIP");
        panellupapassword.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 88, 50, 20));

        jLabel8.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText(":");
        panellupapassword.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 167, 50, 20));

        jLabel9.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText(":");
        panellupapassword.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 50, 20));

        jLabel10.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText(":");
        panellupapassword.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 251, 50, 20));

        jLabel11.setFont(new java.awt.Font("Noto Serif", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText(":");
        panellupapassword.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 85, 50, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panel/panellupapassword.png"))); // NOI18N
        jLabel6.setOpaque(true);
        panellupapassword.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellupapassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panellupapassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanlupapasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanlupapasswordActionPerformed
        if(txt_niplupapassword.getText().equals("")||txt_namalupapassword.getText().equals("")||txt_usernamelupapassword.getText().equals("")||
        txt_passlupapassword.getText().equals("")||txt_pass2lupapassword.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Lupa Password", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(txt_passlupapassword.getText().equals(txt_pass2lupapassword.getText())){
                Object[] obj=new Object[3];
                try{
                    sql = "SELECT * FROM admin WHERE username='"+txt_usernamelupapassword.getText()+"' AND nip='"+txt_niplupapassword.getText()+"' AND nama='"+txt_namalupapassword.getText()+"' "
                            + "AND status='Aktif'";
                    rs = stat.executeQuery(sql);
                    while(rs.next()){
                        obj[0]=rs.getString("nip");
                        obj[1]=rs.getString("nama");
                        obj[2]=rs.getString("username");
                        System.out.println(obj[0]);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(lupapassword.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(obj[0]==null && obj[1]==null & obj[2]==null){
                    JOptionPane.showMessageDialog(null, "Data Admin Tidak Ditemukan", "Lupa Password", JOptionPane.ERROR_MESSAGE);
                }
                else{
                   try{
                    stat = con.createStatement( );
                    con.createStatement().executeUpdate("UPDATE admin set   password=MD5('"+txt_passlupapassword.getText()+"') "
                                                                        + "WHERE nip='"+txt_niplupapassword.getText()+"' AND username='"+txt_usernamelupapassword.getText()+"'"
                                                                                + " AND nama='"+txt_namalupapassword.getText()+"' AND status='Aktif'");
                    rs   = stat.executeQuery(sql);
                    JOptionPane.showMessageDialog(null, "Data Password Sudah Diperbaharui", "Lupa Password", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(lupapassword.class.getName()).log(Level.SEVERE, null, ex);
                } 
                }
                
            }
            else{
             JOptionPane.showMessageDialog(null, "Password baru dengan tulis ulang password tidak sama", "Lupa Password", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpanlupapasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupapassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupapassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpanlupapassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panellupapassword;
    private javax.swing.JTextField txt_namalupapassword;
    private javax.swing.JTextField txt_niplupapassword;
    private javax.swing.JPasswordField txt_pass2lupapassword;
    private javax.swing.JPasswordField txt_passlupapassword;
    private javax.swing.JTextField txt_usernamelupapassword;
    // End of variables declaration//GEN-END:variables
}
